#!/bin/bash

alias ls='lsd'
alias catt='/bin/cat'
alias cat='bat'
alias vim='nvim'
alias sdn='shutdown now'
alias grep='grep --color=auto'

alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'

export PATH="$HOME/development/flutter/bin:$PATH"

